// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/CreateLinkForm.tsx";
import * as $$1 from "./islands/GlobalAlert.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/CreateLinkForm.tsx": $$0,
    "./islands/GlobalAlert.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
